apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: microbot
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: microbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        container.apparmor.security.beta.kubernetes.io/microbot: runtime/default
        ##container.apparmor.security.beta.kubernetes.io/microbot: localhost/k8s-apparmor-example-deny-write
      labels:
        run: microbot
    spec:
      containers:
      - image: dontrebootme/microbot:v{{ .Values.version }}
        name: microbot
        ports:
        - containerPort: 80
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: microbot
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: microbot
  type: NodePort
status:
  loadBalancer: {}

